export interface Booking {
  id: string;
  name: string;
  user: string;
  description: string;
  attendees: number;
  room: string;
  location: string;
  date: string;
  time: string;
  status: 'Upcoming' | 'Completed' | 'Cancelled' | 'Approved' | 'Pending' | 'Declined';
  recurrence: 'recurring' | 'non-recurring';
  roomCode?: string; // Optional field for room code
  roomName?: string; // Optional field for room name
}

export const sampleBookingList: Booking[] = [
  {
    id: 'MTG12',
    name: 'Investor Town Hall',
    user: 'Alice Smith',
    description: 'Quarterly update for investors.',
    attendees: 120,
    room: 'Upcoming Booking GH-200 (Grand Auditorium)',
    location: 'Main Lobby, Level 1',
    date: '28-April-2024',
    time: '16:00-18:30',
    status: 'Cancelled',
    recurrence: 'recurring',
    roomCode: 'GH-200',
    roomName: 'Grand Auditorium',
  },
  {
    id: 'MTG13',
    name: 'Product Strategy Meeting',
    user: 'Bob Jones',
    description: 'Discuss product roadmap and milestones.',
    attendees: 15,
    room: 'Conf Room A-101',
    location: 'Tower B, 3rd Floor',
    date: '05-May-2025',
    time: '10:00-12:00',
    status: 'Upcoming',
    recurrence: 'recurring',
    roomCode: 'A-101',
    roomName: 'Conf Room A-101',
  },
  {
    id: 'MTG14',
    name: 'Client Pitch Meeting',
    user: 'Carol Lee',
    description: 'Pitching new solutions to client.',
    attendees: 8,
    room: 'Conf Room B-202',
    location: 'Tower C, 5th Floor',
    date: '15-May-2025',
    time: '14:00-15:30',
    status: 'Upcoming',
    recurrence: 'non-recurring',
    roomCode: 'B-202',
    roomName: 'Conf Room B-202',
  },
  {
    id: 'MTG15',
    name: 'Annual Financial Review',
    user: 'David Kim',
    description: 'Review of annual financial statements.',
    attendees: 20,
    room: 'Boardroom C-305',
    location: 'Tower A, 10th Floor',
    date: '12-June-2024',
    time: '09:00-11:00',
    status: 'Completed',
    recurrence: 'recurring',
    roomCode: 'C-305',
    roomName: 'Boardroom C-305',
  },
  {
    id: 'MTG16',
    name: 'Team Building Workshop',
    user: 'Emma Wilson',
    description: 'Interactive workshop for team bonding.',
    attendees: 30,
    room: 'Conf Room A-102',
    location: 'Main Building, 2nd Floor',
    date: '23-June-2025',
    time: '13:30-16:00',
    status: 'Cancelled',
    recurrence: 'non-recurring',
    roomCode: 'A-102',
    roomName: 'Conf Room A-102',
  },
  {
    id: 'MTG17',
    name: 'Quarterly Sales Meeting',
    user: 'Frank Miller',
    description: 'Review of quarterly sales performance.',
    attendees: 25,
    room: 'Conference Room D-404',
    location: 'Tower B, 7th Floor',
    date: '05-July-2025',
    time: '11:00-12:30',
    status: 'Upcoming',
    recurrence: 'recurring',
    roomCode: 'D-404',
    roomName: 'Conference Room D-404',
  },
  {
    id: 'MTG18',
    name: 'Leadership Summit',
    user: 'Grace Hall',
    description: 'Summit for company leadership.',
    attendees: 50,
    room: 'Grand Ballroom D-502',
    location: 'Level 4, Tower C',
    date: '28-July-2025',
    time: '15:00-18:00',
    status: 'Upcoming',
    recurrence: 'non-recurring',
    roomCode: 'D-502',
    roomName: 'Grand Ballroom',
  },
  {
    id: 'MTG19',
    name: 'Innovation Workshop',
    user: 'Henry Adams',
    description: 'Workshop on innovative business ideas.',
    attendees: 18,
    room: 'Innovation Lab A-301',
    location: 'Tower D, 3rd Floor',
    date: '12-August-2024',
    time: '09:00-12:00',
    status: 'Completed',
    recurrence: 'non-recurring',
    roomCode: 'A-301',
    roomName: 'Innovation Lab',
  },
  {
    id: 'MTG20',
    name: 'Product Launch Event',
    user: 'Isabel Moore',
    description: 'Launch of new product line.',
    attendees: 200,
    room: 'Grand Auditorium E-701',
    location: 'Level 8, Tower A',
    date: '03-September-2025',
    time: '14:00-17:00',
    status: 'Upcoming',
    recurrence: 'non-recurring',
    roomCode: 'E-701',
    roomName: 'Grand Auditorium',
  },
  {
    id: 'MTG21',
    name: 'CEO Keynote',
    user: 'John Doe',
    description: 'Keynote speech by CEO.',
    attendees: 300,
    room: 'Main Stage F-601',
    location: 'Event Hall, Level 6',
    date: '10-September-2025',
    time: '10:00-11:30',
    status: 'Cancelled',
    recurrence: 'recurring',
    roomCode: 'F-601',
    roomName: 'Main Stage',
  },
  {
    id: 'MTG22',
    name: 'Customer Success Meeting',
    user: 'Karen Chan',
    description: 'Meeting with customer success team.',
    attendees: 12,
    room: 'Customer Room G-104',
    location: 'Tower B, 4th Floor',
    date: '01-October-2024',
    time: '13:00-15:00',
    status: 'Completed',
    recurrence: 'recurring',
    roomCode: 'G-104',
    roomName: 'Customer Room',
  },
  {
    id: 'MTG23',
    name: 'Digital Transformation Summit',
    user: 'Liam Evans',
    description: 'Summit on digital transformation.',
    attendees: 80,
    room: 'Summit Room H-202',
    location: 'Tower A, 2nd Floor',
    date: '17-October-2025',
    time: '09:00-11:00',
    status: 'Upcoming',
    recurrence: 'non-recurring',
    roomCode: 'H-202',
    roomName: 'Summit Room',
  },
  {
    id: 'MTG24',
    name: 'Marketing Strategy Session',
    user: 'Mia Taylor',
    description: 'Session to plan marketing strategies.',
    attendees: 10,
    room: 'Marketing Room I-303',
    location: 'Tower C, 3rd Floor',
    date: '22-October-2024',
    time: '14:00-16:30',
    status: 'Completed',
    recurrence: 'non-recurring',
    roomCode: 'I-303',
    roomName: 'Marketing Room',
  },
  {
    id: 'MTG25',
    name: 'Team Retreat Planning',
    user: 'Noah Brown',
    description: 'Planning for annual team retreat.',
    attendees: 6,
    room: 'Conf Room J-201',
    location: 'Tower D, 1st Floor',
    date: '04-November-2025',
    time: '10:00-13:00',
    status: 'Upcoming',
    recurrence: 'non-recurring',
    roomCode: 'J-201',
    roomName: 'Conf Room J-201',
  },
  {
    id: 'MTG26',
    name: 'Global Expansion Meeting',
    user: 'Olivia Green',
    description: 'Discussion on global expansion plans.',
    attendees: 14,
    room: 'Room K-503',
    location: 'Tower E, 5th Floor',
    date: '18-November-2024',
    time: '15:00-17:00',
    status: 'Completed',
    recurrence: 'recurring',
    roomCode: 'K-503',
    roomName: 'Room K-503',
  },
  {
    id: 'MTG27',
    name: 'Tech Talk: AI in Business',
    user: 'Peter White',
    description: 'Talk on AI applications in business.',
    attendees: 40,
    room: 'Tech Room L-306',
    location: 'Tower C, 6th Floor',
    date: '02-December-2025',
    time: '13:30-15:00',
    status: 'Upcoming',
    recurrence: 'recurring',
    roomCode: 'L-306',
    roomName: 'Tech Room',
  },
  {
    id: 'MTG28',
    name: 'Investor Roundtable',
    user: 'Quinn Harris',
    description: 'Roundtable with key investors.',
    attendees: 22,
    room: 'Roundtable Room M-401',
    location: 'Tower A, 4th Floor',
    date: '20-January-2024',
    time: '11:00-13:00',
    status: 'Completed',
    recurrence: 'recurring',
    roomCode: 'M-401',
    roomName: 'Roundtable Room',
  },
  {
    id: 'MTG29',
    name: 'Corporate Social Responsibility Meeting',
    user: 'Rachel King',
    description: 'CSR initiatives planning.',
    attendees: 16,
    room: 'CSR Room N-201',
    location: 'Tower B, 2nd Floor',
    date: '15-February-2025',
    time: '14:00-16:00',
    status: 'Upcoming',
    recurrence: 'non-recurring',
    roomCode: 'N-201',
    roomName: 'CSR Room',
  },
  {
    id: 'MTG30',
    name: 'Annual Budget Planning',
    user: 'Samuel Martin',
    description: 'Planning for next year’s budget.',
    attendees: 11,
    room: 'Finance Room O-505',
    location: 'Tower C, 5th Floor',
    date: '01-March-2025',
    time: '09:00-12:00',
    status: 'Upcoming',
    recurrence: 'recurring',
    roomCode: 'O-505',
    roomName: 'Finance Room',
  },
];

export const bookingHistory: Booking[] = [
  {
    id: 'B001',
    name: 'John Smith',
    room: 'Meeting Room 1',
    location: 'HQ, Level 3',
    date: '2023-10-01',
    time: '10:00 AM - 11:00 AM',
    status: 'Completed',
  },
  {
    id: 'B002',
    name: 'Jane Doe',
    room: 'Conference Room B',
    location: 'HQ, Level 5',
    date: '2023-10-02',
    time: '1:00 PM - 2:00 PM',
    status: 'Cancelled',
  },
];

export const reservations: Booking[] = [
  {
    id: 'B003',
    name: 'Alice Johnson',
    room: 'Conference Room A',
    location: 'Branch 1, Level 5',
    date: '2023-10-05',
    time: '2:00 PM - 3:00 PM',
    status: 'Upcoming', 
  },
  {
    id: 'B004',
    name: 'Bob Williams',
    room: 'Meeting Room 2',
    location: 'Branch 2, Level 2',
    date: '2023-10-06',
    time: '9:00 AM - 10:00 AM',
    status: 'Upcoming', 
  },
];