export interface Booking {
    id: string;
    name: string;
    room: string;
    location: string;
    date: string;
    time: string;
    status: 'Upcoming' | 'Completed' | 'Cancelled';
  }

export const sampleBookingList: Booking[] = [
  {
    id: 'MTG12',
    name: 'Investor Town Hall',
    room: 'Upcoming Booking GH-200 (Grand Auditorium)',
    location: 'Main Lobby, Level 1',
    date: '28-April-2024',
    time: '16:00-18:30',
    status: 'Cancelled',
  },
  {
    id: 'MTG13',
    name: 'Product Strategy Meeting',
    room: 'Conf Room A-101',
    location: 'Tower B, 3rd Floor',
    date: '05-May-2025',
    time: '10:00-12:00',
    status: 'Upcoming',
  },
  {
    id: 'MTG14',
    name: 'Client Pitch Meeting',
    room: 'Conf Room B-202',
    location: 'Tower C, 5th Floor',
    date: '15-May-2025',
    time: '14:00-15:30',
    status: 'Upcoming',
  },
  {
    id: 'MTG15',
    name: 'Annual Financial Review',
    room: 'Boardroom C-305',
    location: 'Tower A, 10th Floor',
    date: '12-June-2024',
    time: '09:00-11:00',
    status: 'Completed',
  },
  {
    id: 'MTG16',
    name: 'Team Building Workshop',
    room: 'Conf Room A-102',
    location: 'Main Building, 2nd Floor',
    date: '23-June-2025',
    time: '13:30-16:00',
    status: 'Cancelled',
  },
  {
    id: 'MTG17',
    name: 'Quarterly Sales Meeting',
    room: 'Conference Room D-404',
    location: 'Tower B, 7th Floor',
    date: '05-July-2025',
    time: '11:00-12:30',
    status: 'Upcoming',
  },
  {
    id: 'MTG18',
    name: 'Leadership Summit',
    room: 'Grand Ballroom D-502',
    location: 'Level 4, Tower C',
    date: '28-July-2025',
    time: '15:00-18:00',
    status: 'Upcoming',
  },
  {
    id: 'MTG19',
    name: 'Innovation Workshop',
    room: 'Innovation Lab A-301',
    location: 'Tower D, 3rd Floor',
    date: '12-August-2024',
    time: '09:00-12:00',
    status: 'Completed',
  },
  {
    id: 'MTG20',
    name: 'Product Launch Event',
    room: 'Grand Auditorium E-701',
    location: 'Level 8, Tower A',
    date: '03-September-2025',
    time: '14:00-17:00',
    status: 'Upcoming',
  },
  {
    id: 'MTG21',
    name: 'CEO Keynote',
    room: 'Main Stage F-601',
    location: 'Event Hall, Level 6',
    date: '10-September-2025',
    time: '10:00-11:30',
    status: 'Cancelled',
  },
  {
    id: 'MTG22',
    name: 'Customer Success Meeting',
    room: 'Customer Room G-104',
    location: 'Tower B, 4th Floor',
    date: '01-October-2024',
    time: '13:00-15:00',
    status: 'Completed',
  },
  {
    id: 'MTG23',
    name: 'Digital Transformation Summit',
    room: 'Summit Room H-202',
    location: 'Tower A, 2nd Floor',
    date: '17-October-2025',
    time: '09:00-11:00',
    status: 'Upcoming',
  },
  {
    id: 'MTG24',
    name: 'Marketing Strategy Session',
    room: 'Marketing Room I-303',
    location: 'Tower C, 3rd Floor',
    date: '22-October-2024',
    time: '14:00-16:30',
    status: 'Completed',
  },
  {
    id: 'MTG25',
    name: 'Team Retreat Planning',
    room: 'Conf Room J-201',
    location: 'Tower D, 1st Floor',
    date: '04-November-2025',
    time: '10:00-13:00',
    status: 'Upcoming',
  },
  {
    id: 'MTG26',
    name: 'Global Expansion Meeting',
    room: 'Room K-503',
    location: 'Tower E, 5th Floor',
    date: '18-November-2024',
    time: '15:00-17:00',
    status: 'Completed',
  },
  {
    id: 'MTG27',
    name: 'Tech Talk: AI in Business',
    room: 'Tech Room L-306',
    location: 'Tower C, 6th Floor',
    date: '02-December-2025',
    time: '13:30-15:00',
    status: 'Upcoming',
  },
  {
    id: 'MTG28',
    name: 'Investor Roundtable',
    room: 'Roundtable Room M-401',
    location: 'Tower A, 4th Floor',
    date: '20-January-2024',
    time: '11:00-13:00',
    status: 'Completed',
  },
  {
    id: 'MTG29',
    name: 'Corporate Social Responsibility Meeting',
    room: 'CSR Room N-201',
    location: 'Tower B, 2nd Floor',
    date: '15-February-2025',
    time: '14:00-16:00',
    status: 'Upcoming',
  },
  {
    id: 'MTG30',
    name: 'Annual Budget Planning',
    room: 'Finance Room O-505',
    location: 'Tower C, 5th Floor',
    date: '01-March-2025',
    time: '09:00-12:00',
    status: 'Upcoming',
  }
];
  